#
#  Copyright 2015 VMware, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
---
- name: assure dnsmasq installed
  apt: pkg=dnsmasq state=present

- name: enable dnsmasq service at boot
  service: name=dnsmasq state=started enabled=True

- name: remove default config file loading
  lineinfile:
    dest=/etc/default/dnsmasq
    regexp='^CONFIG_DIR='
    state=absent
  notify:
    - restart dnsmasq

- name: setup main configuration file
  template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.conf mode=0644
  notify:
    - restart dnsmasq

- name: make sure the extra config directory exists
  file: dest={{ dnsmasq_etc_path }} state=directory recurse=yes mode=0755

- name: setup resolver forwards
  template: src=resolv.dnsmasq.j2 dest={{ dnsmasq_etc_path }}/resolv.dnsmasq mode=0644
  notify:
    - restart dnsmasq
  when: dnsmasq_nameservers is defined

- name: setup dhcp (static) reservations
  template: src=dhcp-hosts.j2 dest={{ dnsmasq_dhcp_hosts }} mode=0644
  notify:
    - restart dnsmasq
  when: dnsmasq_dhcp_hosts is defined

- name: make sure the additional hosts config directory exists
  file: dest={{ dnsmasq_etc_path }}/hosts state=directory recurse=yes mode=0755

- name: setup additional hosts  dnsmasq configuration file
  template: src=addn-hosts.j2 dest={{ dnsmasq_etc_path }}/hosts/hosts.dnsmasq mode=0644
  notify:
    - restart dnsmasq
  when: dnsmasq_additional_hosts is defined

- name: setup network interfaces
  template: src=Debian/interfaces.j2 dest=/etc/network/interfaces mode=0644
  notify:
    - reboot server
  when: dnsmasq_dhcp_hosts
